### ISSUE TITLE
Tidak bisa scan QR, muncul error seperti ini

### ISSUE THREAD

**Issue by ridosimbolon98** [mhmdmydn/bot-whatsapp#1]
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be of type string or an instance of ArrayBuffer, Buffer, TypedArray, DataView, KeyObject, or CryptoKey. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at prepareSecretKey (node:internal/crypto/keys:570:11)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:133:9)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at Object.aesEncrypt (C:\Bitnami\wappstack-7.4.27-0\apache2\htdocs\bot-whatsapp-main\node_modules\@adiwajshing\baileys\lib\WAConnection\Utils.js:108:24)
    at WAConnection.sendBinary (C:\Bitnami\wappstack-7.4.27-0\apache2\htdocs\bot-whatsapp-main\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:321:26)
    at WAConnection.<anonymous> (C:\Bitnami\wappstack-7.4.27-0\apache2\htdocs\bot-whatsapp-main\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:86:18)
    at WAConnection.emit (node:events:402:35)
    at WAConnection.emit (C:\Bitnami\wappstack-7.4.27-0\apache2\htdocs\bot-whatsapp-main\node_modules\@adiwajshing\baileys\lib\WAConnection\4.Events.js:664:41) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by mhmdmydn** [comment]
Coba di update bang library soalnya udah ada yang terbaru  [Baileys](https://github.com/adiwajshing/Baileys)

**Comment by ridosimbolon98** [comment]
Sekarang munculnya gini bg

const conn = new WAConnection();
                 ^

TypeError: WAConnection is not a constructor
    at Object.exports.start (C:\Bitnami\wappstack-7.4.27-0\apache2\htdocs\bot-whatsapp\app\message\bot.js:15:18)
    at Namespace.<anonymous> (C:\Bitnami\wappstack-7.4.27-0\apache2\htdocs\bot-whatsapp\server.js:24:6)
    at Namespace.emit (node:events:390:28)
    at Namespace.emitReserved (C:\Bitnami\wappstack-7.4.27-0\apache2\htdocs\bot-whatsapp\node_modules\socket.io\dist\typed-events.js:56:22)
    at C:\Bitnami\wappstack-7.4.27-0\apache2\htdocs\bot-whatsapp\node_modules\socket.io\dist\namespace.js:141:26
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
